### ISSUE TITLE
Completely Stuck

### ISSUE THREAD

**Issue by JStrouhal00** [JStrouhal00/UnityE-safetyGame#2]
So what I'm trying to do is write the code that will allow the program to "draw" a card from the deck. To do this, I've already got the three prototype cards in a list/array, and their order is shuffled.

What I can't figure out is how to access, and then iterate through, that array, which is why it's only ever been "Card 1" that gets moved by the program. The problem seems to stem from the fact I'm using a custom data type - "Cards" (e.g. Cards.cardList etc.) - and functions like "Translate" and "Rotate" apply to default "GameObject"s. (See the images for a better description) So is there any way I can convert to "GameObject", or do I have to come up with an alternative solution?

<img width="960" alt="CurrentLook" src="https://user-images.githubusercontent.com/60967701/77770054-921dda00-703c-11ea-8978-e93d56b53547.png">
<img width="960" alt="ShuffleFeature" src="https://user-images.githubusercontent.com/60967701/77770074-9b0eab80-703c-11ea-93ee-9faab02f2d05.png">

**Comment by Danni87** [comment]
I’m working on it to find a solution.

**Comment by Danni87** [comment]
The problem is that you don't have a connection between a game object and the card abstraction. Basically what you are shuffling are the card abstractions but not the objects themselves. What you could do is either have the card data on a component on the card game object, or use the cards as a front end for the data. Hope it helps .

**Comment by JStrouhal00** [comment]
Okay, honestly, that sounds kinda complicated to me. Since you already seem to understand the problem and what the solution is, would it be okay for you to do this?

**Comment by Danni87** [comment]
I could only understand the problem because I have done hours of research. I did my part and more than my part to be fair and also got more projects to work on. I have given you the solution so you will be able to solve the problem if you put some more time. 
you put the time and do the research, if you still need help I'm here :)

**Comment by JStrouhal00** [comment]
Okay, that's fair.

Don't know how long it'll take, but I'll get it done as quickly as I can.

**Comment by Danni87** [comment]
I have attached a question card project in Unity , It would be very helpful for you to find out a solution. Any problem just ask me .
[CardExample.zip](https://github.com/JStrouhal00/UnityE-safetyGame/files/4417916/CardExample.zip)

**Comment by JStrouhal00** [comment]
Okay, wow, yeah, this looks like it'll be a huge help. Thanks!

**Comment by JStrouhal00** [comment]
I got it working! Huge thanks, Dan, the example you provided worked wonderfully.
